//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TestPAWeb.EventiWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EventiSoap", Namespace="http://saia.ancitel.it/xmlmanager/ap5")]
    public partial class Eventi : Microsoft.Web.Services2.WebServicesClientProtocol {
        
        private LogHeader logHeaderValueField;
        
        private System.Threading.SendOrPostCallback VariazioniAnagraficheOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Eventi() {
            this.Url = global::TestPAWeb.Properties.Settings.Default.TestPAWeb_EventiWS_Eventi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public LogHeader LogHeaderValue {
            get {
                return this.logHeaderValueField;
            }
            set {
                this.logHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VariazioniAnagraficheCompletedEventHandler VariazioniAnagraficheCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LogHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://saia.ancitel.it/xmlmanager/ap5/VariazioniAnagrafiche", RequestNamespace="http://saia.ancitel.it/xmlmanager/ap5", ResponseNamespace="http://saia.ancitel.it/xmlmanager/ap5", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode VariazioniAnagrafiche(int Giorno, int Mese, int Anno, string CodiceEvento, byte ServiceLevel) {
            object[] results = this.Invoke("VariazioniAnagrafiche", new object[] {
                        Giorno,
                        Mese,
                        Anno,
                        CodiceEvento,
                        ServiceLevel});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void VariazioniAnagraficheAsync(int Giorno, int Mese, int Anno, string CodiceEvento, byte ServiceLevel) {
            this.VariazioniAnagraficheAsync(Giorno, Mese, Anno, CodiceEvento, ServiceLevel, null);
        }
        
        /// <remarks/>
        public void VariazioniAnagraficheAsync(int Giorno, int Mese, int Anno, string CodiceEvento, byte ServiceLevel, object userState) {
            if ((this.VariazioniAnagraficheOperationCompleted == null)) {
                this.VariazioniAnagraficheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVariazioniAnagraficheOperationCompleted);
            }
            this.InvokeAsync("VariazioniAnagrafiche", new object[] {
                        Giorno,
                        Mese,
                        Anno,
                        CodiceEvento,
                        ServiceLevel}, this.VariazioniAnagraficheOperationCompleted, userState);
        }
        
        private void OnVariazioniAnagraficheOperationCompleted(object arg) {
            if ((this.VariazioniAnagraficheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VariazioniAnagraficheCompleted(this, new VariazioniAnagraficheCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://saia.ancitel.it/xmlmanager/ap5")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://saia.ancitel.it/xmlmanager/ap5", IsNullable=false)]
    public partial class LogHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string logGuidField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string LogGuid {
            get {
                return this.logGuidField;
            }
            set {
                this.logGuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void VariazioniAnagraficheCompletedEventHandler(object sender, VariazioniAnagraficheCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VariazioniAnagraficheCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VariazioniAnagraficheCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591